// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vm_api_backend_appservice.Data;

#nullable disable

namespace vm_api_backend_appservice.Migrations
{
    [DbContext(typeof(VmDbContext))]
    partial class VmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("vm_api_backend_appservice.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StatusEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#4CAF50",
                            Description = "The virtual machine is running",
                            Name = "Running",
                            StatusEnum = 0
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#F44336",
                            Description = "The virtual machine is stopped",
                            Name = "Stopped",
                            StatusEnum = 1
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#2196F3",
                            Description = "The virtual machine is being provisioned",
                            Name = "Provisioning",
                            StatusEnum = 2
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#FF9800",
                            Description = "The virtual machine has failed",
                            Name = "Failed",
                            StatusEnum = 3
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "#9C27B0",
                            Description = "The virtual machine is suspended",
                            Name = "Suspended",
                            StatusEnum = 4
                        },
                        new
                        {
                            Id = 6,
                            ColorCode = "#607D8B",
                            Description = "The virtual machine is under maintenance",
                            Name = "Maintenance",
                            StatusEnum = 5
                        });
                });

            modelBuilder.Entity("vm_api_backend_appservice.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 14, 11, 13, 4, 65, DateTimeKind.Utc).AddTicks(4304),
                            Email = "admin@vmapi.com",
                            Name = "Admin User",
                            Password = "$2a$11$S0LmeQQVgqh0znOUk/8QjuKkAFQ06sMLcAaVFmtJo2Q.KiJXt5C6S",
                            Role = 0,
                            UpdatedAt = new DateTime(2025, 4, 14, 11, 13, 4, 65, DateTimeKind.Utc).AddTicks(4311)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 14, 11, 13, 4, 189, DateTimeKind.Utc).AddTicks(2275),
                            Email = "client@vmapi.com",
                            Name = "Client User",
                            Password = "$2a$11$M6Zby0FXF4ovJbQtlLT9kuk5dPYQ8mKhtfsouGMNW9A4L4pyQ8Epm",
                            Role = 1,
                            UpdatedAt = new DateTime(2025, 4, 14, 11, 13, 4, 189, DateTimeKind.Utc).AddTicks(2280)
                        });
                });

            modelBuilder.Entity("vm_api_backend_appservice.Models.VirtualMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("Disk")
                        .HasColumnType("int");

                    b.Property<string>("Hostname")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OperatingSystemId")
                        .HasColumnType("int");

                    b.Property<int>("Ram")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OperatingSystemId");

                    b.HasIndex("StatusId");

                    b.ToTable("VirtualMachines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cores = 4,
                            CreatedAt = new DateTime(2025, 4, 14, 11, 13, 4, 189, DateTimeKind.Utc).AddTicks(3496),
                            Description = "Main web server",
                            Disk = 500,
                            Hostname = "web-srv-01",
                            IpAddress = "10.0.0.10",
                            Name = "Web Server",
                            OperatingSystemId = 5,
                            Ram = 16,
                            StatusId = 1,
                            UpdatedAt = new DateTime(2025, 4, 14, 11, 13, 4, 189, DateTimeKind.Utc).AddTicks(3497)
                        },
                        new
                        {
                            Id = 2,
                            Cores = 8,
                            CreatedAt = new DateTime(2025, 4, 14, 11, 13, 4, 189, DateTimeKind.Utc).AddTicks(3501),
                            Description = "Main database server",
                            Disk = 1000,
                            Hostname = "db-srv-01",
                            IpAddress = "10.0.0.11",
                            Name = "Database Server",
                            OperatingSystemId = 2,
                            Ram = 32,
                            StatusId = 1,
                            UpdatedAt = new DateTime(2025, 4, 14, 11, 13, 4, 189, DateTimeKind.Utc).AddTicks(3501)
                        },
                        new
                        {
                            Id = 3,
                            Cores = 2,
                            CreatedAt = new DateTime(2025, 4, 14, 11, 13, 4, 189, DateTimeKind.Utc).AddTicks(3505),
                            Description = "Testing environment",
                            Disk = 250,
                            Hostname = "test-srv-01",
                            IpAddress = "10.0.0.12",
                            Name = "Test Environment",
                            OperatingSystemId = 7,
                            Ram = 8,
                            StatusId = 2,
                            UpdatedAt = new DateTime(2025, 4, 14, 11, 13, 4, 189, DateTimeKind.Utc).AddTicks(3505)
                        });
                });

            modelBuilder.Entity("vm_api_backend_appservice.Models.VmOperatingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OsType")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("OperatingSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Microsoft Windows Server 2019",
                            IsActive = true,
                            Name = "Windows Server 2019",
                            OsType = 0,
                            Version = "2019"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Microsoft Windows Server 2022",
                            IsActive = true,
                            Name = "Windows Server 2022",
                            OsType = 1,
                            Version = "2022"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ubuntu 18.04 Long Term Support",
                            IsActive = true,
                            Name = "Ubuntu 18.04 LTS",
                            OsType = 2,
                            Version = "18.04"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ubuntu 20.04 Long Term Support",
                            IsActive = true,
                            Name = "Ubuntu 20.04 LTS",
                            OsType = 3,
                            Version = "20.04"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ubuntu 22.04 Long Term Support",
                            IsActive = true,
                            Name = "Ubuntu 22.04 LTS",
                            OsType = 4,
                            Version = "22.04"
                        },
                        new
                        {
                            Id = 6,
                            Description = "CentOS Linux 7",
                            IsActive = true,
                            Name = "CentOS 7",
                            OsType = 7,
                            Version = "7"
                        },
                        new
                        {
                            Id = 7,
                            Description = "CentOS Linux 8",
                            IsActive = true,
                            Name = "CentOS 8",
                            OsType = 8,
                            Version = "8"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Debian 10 (Buster)",
                            IsActive = true,
                            Name = "Debian 10",
                            OsType = 5,
                            Version = "10"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Debian 11 (Bullseye)",
                            IsActive = true,
                            Name = "Debian 11",
                            OsType = 6,
                            Version = "11"
                        });
                });

            modelBuilder.Entity("vm_api_backend_appservice.Models.VirtualMachine", b =>
                {
                    b.HasOne("vm_api_backend_appservice.Models.VmOperatingSystem", "OperatingSystem")
                        .WithMany("VirtualMachines")
                        .HasForeignKey("OperatingSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vm_api_backend_appservice.Models.Status", "Status")
                        .WithMany("VirtualMachines")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperatingSystem");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("vm_api_backend_appservice.Models.Status", b =>
                {
                    b.Navigation("VirtualMachines");
                });

            modelBuilder.Entity("vm_api_backend_appservice.Models.VmOperatingSystem", b =>
                {
                    b.Navigation("VirtualMachines");
                });
#pragma warning restore 612, 618
        }
    }
}
